version: "3"
services:
  redis:
    image: redis:latest
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - ./tmp/db:/var/lib/postgresql@15/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${POSTGRES_PORT}:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - "db:database"
    env_file:
      - .env
    stdin_open: true
    tty: true
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    links:
      - "db:database"
    volumes:
      - .:/myapp
    env_file:
      - .env
    stdin_open: true
    tty: true